### ISSUE TITLE
How can I lookup previously generated reports?

### ISSUE THREAD

**Issue by chrisjmccrum** [maxmind/minfraud-api-dotnet#164]
When I generate a factor's report, I also store the maxmind id associated with the report. Is there a way to lookup these reports with the id in the API? I noticed we had some gaps in our IP Address traits data and would like to back-populate our database with the missing values by querying the API. I understand if this counts against our API limits. Regenerating the reports is not feasible as the scores on older data will likely change.

**Comment by oschwald** [comment]
Unfortunately, there is not a public API to retrieve past transactions like this. You can view past transactions on the account portal of the MaxMind website. [support@maxmind.com](mailto:support@maxmind.com) may also have other suggestions.
