### ISSUE TITLE
Incorrect usageof HttpClient.

### ISSUE THREAD

**Issue by zomgNoUsername** [maxmind/minfraud-api-dotnet#29]
Hi, did you realize the way you're using HttpClient is not correct?

[For example](https://github.com/maxmind/minfraud-api-dotnet/blob/master/MaxMind.MinFraud/WebServiceClient.cs#L67)

Here is some more info: http://byterot.blogspot.com.au/2016/07/singleton-httpclient-dns.html

I'll attach some sample code I use as a basis when adding HttpClient to my projects: https://gist.github.com/zomgNoUsername/a99689e78329f79262246b5de56de98d

**Comment by oschwald** [comment]
Thanks for the report. Is this causing a particular issue for you? As far as I can tell, the underlying problem identified in that article is that persistent connections are not closed voluntarily and thus don't respond to DNS changes. We rarely make DNS changes, and, even if we did, as long as the connection persists, we should be able to continue responding to requests from it.

**Comment by zomgNoUsername** [comment]
If the DNS never changes, that's good; as you don't need to worry about the connection lease timeout property on the ServicePointManager.

But the main concern here would be the inefficient use of sockets, and keep-alive connections.

If HttpClient is disposed after each use, that means it no uses the same socket for the next http request, which means it must make a brand new tcp connection with the same host as before (like http 1.0 did).

Also that socket it disposed of is not usable again for another 240 seconds.  
If you're making a lot if requests (like we are), you'll need double the servers to get the same perf you used to get from using any other client (such as WebClient, or HttpWebRequest).

**Comment by oschwald** [comment]
I am confused, we don't dispose of `HttpClient` after each use, which is why the DNS issue mentioned in the article could plausible matter (but doesn't really matter in our case). We create the `HttpClient` in the constructor and continue to use it as long as the object lives. The object should be used for multiple requests in most cases.

**Comment by zomgNoUsername** [comment]
You're absolutely correct.

My concern is that your api is easy to use incorrectly, by writing idiomatic C# code. 
In the [usage](https://github.com/maxmind/minfraud-api-dotnet#usage) example this is how I perceive developers will use it.

```cs
using (var client = new WebServiceClient(10, "LICENSEKEY"))
{
    // Use client methods here.
}
```

How does a consumer of your nuget package know your internal implementation is a HttpClient that only lives as long as the WebServiceClient instance?

The way .NET decided to implement HttpClient's dispose method is just terrible, and counter-intuitive to how one should deal with any other object's dispose. But that doesn't we have to make the same mistake.

**Comment by zomgNoUsername** [comment]
At the very least, you should document in the readme that only one instance of WebServiceClient should exist for the lifetime of the application, and that it is a threadsafe implementation.
