### ISSUE TITLE
FactorsAsync returns Insights instead of Factors

### ISSUE THREAD

**Issue by bpolovyk** [maxmind/minfraud-api-dotnet#49]
Hi, Guys!

In WebServiceClient you have method FactorsAsync, that really calls Factors, but hides its result and returns Insights

        public async Task<Insights> FactorsAsync(Transaction transaction)
        {
            var factors = await MakeRequest<Factors>(transaction).ConfigureAwait(false);
            factors.IPAddress.SetLocales(_locales);
            return factors;
        }

**Comment by oschwald** [comment]
Thanks for reporting this.
